<a href="https://colab.research.google.com/github/ag12s/CreateWithCodeModules/blob/main/Introduction%20to%20Python/PracticeProblems/BonusPracticeDay3_Solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

You will need to import numpy in the block below to answer the following questions.


In [ ]:
import numpy as np

# 1. NumPy Arrays 
Write a code fragement that computes the average value of a 2D array. Test it on the array:

$$\begin{bmatrix} 0.1 & 0.8 & 0.8\\0.2 & 0.4 & 1.1\\ 1.3 & 0.9 & 1.1\end{bmatrix}$$

Hint: use the `sum` function or the `mean` function.

In [ ]:
# code for 1
A = np.array([[0.1,0.8,0.8],[0.2,0.4,1.1],[1.3,0.9,1.1]])

avg = np.sum(A)/A.size
print(avg)

0.7444444444444444


Alternatively, the `np.average` function does this directly.

In [ ]:
print(np.average(A))

0.7444444444444444


Write a code fragment that computes the average of each column in the above array. 

In [ ]:
# code for 1
col_avg = np.sum(A, axis=0)/A.shape[0]
print(col_avg)

[0.53333333 0.7        1.        ]


#2. Indexing and slicing NumPy Arrays
Create an $n\times n$ 2D array that contains 1s along the edges and 0s everywhere else. For example the $n=4$ array looks like:

$$ \begin{bmatrix} 1 & 1 & 1 & 1\\ 1 & 0 & 0 & 1\\1 & 0 & 0 & 1\\1 & 1 & 1& 1\end{bmatrix} $$
.

Hint: the command np.zeros((n,n)) creates an $n\times n$ array of all 0s or the command np.ones((n,n)) creates an $n\times n$ array of all 1s.

In [ ]:
# code for 2
n = 10

A = np.zeros((n,n))
A[0,:] = 1
A[:,0] = 1
A[:,-1] = 1
A[-1,:] = 1

print(A)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
